#pragma config(Sensor, in1,    potLeft,        sensorPotentiometer)
#pragma config(Sensor, in2,    potRight,       sensorPotentiometer)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           liftMotor1,    tmotorVex393, openLoop)
#pragma config(Motor,  port5,           liftMotor2,    tmotorVex393, openLoop)
#pragma config(Motor,  port6,           pickupMotor,   tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool debugMode = false;
int jump1 = 1;
int jump2 = 1;
unsigned int time = nSysTime;
bool go = true;
const int highest = 1750;
const int baseHeight = 600;
const int pickupHeight = 900;

task main()
{
writeDebugStream("start it up!!");
StartTask(joyControl(),8);
StartTask(buttonControl(),8);

}

task joyControl()
{
	while(true)
	{
		motor[leftMotor]=vexRT[Ch3];
		motor[rightMotor]=vexRT[Ch2];
	}
}

task buttonControl()
{
	while(true){

	}
}
