#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop)           //left motors to port two, regular direction
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed) //right motors to port 3, reversed direction
#pragma config(Motor,  port4,           liftMotor1,     tmotorServoContinuousRotation, openLoop)          //lift side 1 motors to port 4, regular direction
#pragma config(Motor,  port5,           liftMotor2,     tmotorServoContinuousRotation, openLoop)          //lift side 2 motors to port 5, regular direction
#pragma config(Motor,  port6,           pickupMotor,   tmotorServoContinuousRotation, openLoop)           //pickup motors, port 6, regular direction
#pragma config(Sensor, S1,     potLeft,        sensorPotentiometer)
#pragma config(Sensor, S2,     potRight,       sensorPotentiometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)



//Competition Control and Duration Settings
#pragma competitionControl(Competition) //Sets robot to competition mode, can be controlled by the o competition stand
#pragma autonomousDuration(20)          //Autonomous lasts for 20 seconds
#pragma userControlDuration(120)        //User control lasts fro 2 minutes



#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!



void pre_auton() //Setup for when autonomous is started
{
	bStopTasksBetweenModes = true; //When you swap between usercontrol and auton tasks, kill previous task
	Int jump1 = 1;
	Int jump2 = 1;

	jump1 = in1;
	jump2 = in2;
}

task autonomous() //Actual autonomous code
{
	If(jump1==1){

	} else if (jump2==1) {

	} else {

	}
}

void drive_forward() //test function. Doesn't currently work
{
	motor[leftMotor] = 127;
	motor[rightMotor] = 127;
}

task usercontrol() //Interaction with controller starts once this task is initiated.
{

	while (true) //run forever, unless interupted by competition stand.
	{
	  motor[leftMotor]  = (vexRT[Ch3]); //left motors to channel 3(left stick up)
    motor[rightMotor] = (vexRT[Ch2])/2; //right motors to channel 2(right stick up)

    if(vexRT[Btn6U] == 1)         // If button 6U (upper right shoulder button) is pressed:
    {
      motor[pickupMotor] = 127;
    }
    else if(vexRT[Btn6D] ==1){
    	motor[pickupMotor] = -127;
    }
    else{motor[pickupMotor]=0;}

    if(vexRT[Btn5U] == 1)         // If button 6U (upper right shoulder button) is pressed:
    {
      motor[liftMotor1] = 127;
    }
    else if(vexRT[Btn5D] ==1){
    	motor[liftMotor1] = -127;
    }
    else{motor[liftMotor1]=0;}

    if(vexRT[Btn5U] == 1)         // If button 6U (upper right shoulder button) is pressed:
    {
      motor[liftMotor2] = 127;
    }
    else if(vexRT[Btn5D] ==1){
    	motor[liftMotor2] = -127;
    }
    else{motor[liftMotor2]=0;}

	}
}
