#pragma config(Sensor, in1,    potLeft,        sensorPotentiometer)
#pragma config(Sensor, in2,    potRight,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftEncoder1,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightEncoder1,  sensorQuadEncoder)
#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           liftMotor1,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           liftMotor2,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           pickupMotor,   tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)



//Competition Control and Duration Settings
#pragma competitionControl(Competition) //Sets robot to competition mode, can be controlled by the o competition stand
#pragma autonomousDuration(20)          //Autonomous lasts for 20 seconds
#pragma userControlDuration(120)        //User control lasts fro 2 minutes



#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

bool debugMode = false;
int jump1 = 1;
int jump2 = 1;
unsigned int time = nSysTime;
bool go = true;
const int oneRotation = 360;
const int oneBlockTick = oneRotation*2;
const int highest = 800;
const int baseHeight = 700;
const int pickupHeight = 900;
const int raiseTime = 43;
const int oneBlock = 900;
const int turn90 = 90;
int blueFront=0;
int redFront=0;


void MissionImpossible()
{
  //        100 = Tempo
  //          6 = Default octave
  //    Quarter = Default note length
  //        10% = Break between notes
  //
  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(  933,    7); wait1Msec(  75);  // Note(D#, Duration(32th))
  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(  933,    7); wait1Msec(  75);  // Note(D#, Duration(32th))
  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(  933,    7); wait1Msec(  75);  // Note(D#, Duration(32th))
  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(  933,    7); wait1Msec(  75);  // Note(D#, Duration(32th))
  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(  880,    7); wait1Msec(  75);  // Note(D, Duration(32th))
  PlayTone(  933,    7); wait1Msec(  75);  // Note(D#, Duration(32th))
  PlayTone(  988,    7); wait1Msec(  75);  // Note(E, Duration(32th))
  PlayTone( 1047,    7); wait1Msec(  75);  // Note(F, Duration(32th))
  PlayTone( 1109,    7); wait1Msec(  75);  // Note(F#, Duration(32th))
  PlayTone( 1175,    7); wait1Msec(  75);  // Note(G, Duration(32th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1398,   14); wait1Msec( 150);  // Note(A#, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone(  784,   14); wait1Msec( 150);  // Note(C, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1047,   14); wait1Msec( 150);  // Note(F, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone( 1109,   14); wait1Msec( 150);  // Note(F#, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1398,   14); wait1Msec( 150);  // Note(A#, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone(  784,   14); wait1Msec( 150);  // Note(C, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(    0,   27); wait1Msec( 300);  // Note(Rest, Duration(Eighth))
  PlayTone( 1047,   14); wait1Msec( 150);  // Note(F, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone( 1109,   14); wait1Msec( 150);  // Note(F#, Duration(16th))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone( 1398,   14); wait1Msec( 150);  // Note(A#, Duration(16th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(  880,  108); wait1Msec(1200);  // Note(D, Duration(Half))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone( 1398,   14); wait1Msec( 150);  // Note(A#, Duration(16th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(  831,  108); wait1Msec(1200);  // Note(C#, Duration(Half))
  PlayTone(    0,    7); wait1Msec(  75);  // Note(Rest, Duration(32th))
  PlayTone( 1398,   14); wait1Msec( 150);  // Note(A#, Duration(16th))
  PlayTone( 1175,   14); wait1Msec( 150);  // Note(G, Duration(16th))
  PlayTone(  784,  108); wait1Msec(1200);  // Note(C, Duration(Half))
  PlayTone(    0,   14); wait1Msec( 150);  // Note(Rest, Duration(16th))
  PlayTone(  932,   14); wait1Msec( 150);  // Note(A#5, Duration(16th))
  PlayTone(  784,   14); wait1Msec( 150);  // Note(C, Duration(16th))
  return;
}

void pre_auton() //Setup for when autonomous is started
{
	bStopTasksBetweenModes = true; //When you swap between usercontrol and auton tasks, kill previous task
	jump1 = in5;
	jump2 = in6;
	if(jump1==1)
	{
		blueFront=1;
	}
	else if (jump2==1)
	{
		redFront=1;
	}
	else
	{
		blueFront=0;
		redFront=0;
	}
}

void raiseLift(int height){
	motor[liftMotor1]=128;
	motor[liftMotor2]=128;
	wait1Msec(raiseTime*height);
	motor[liftMotor1]=0;
	motor[liftMotor2]=0;
}

void turn(int direction, int amount){
	SensorValue[leftEncoder1]=0;
	SensorValue[rightEncoder1]=0;
	while(SensorValue(leftEncoder1)<(amount*turn90)&&SensorValue(rightEncoder1)<(amount*turn90)){
		if(direction == -1){
			motor[leftMotor]=-127;
			motor[rightMotor]=127;
		}
		else if (direction==1){
			motor[leftMotor]=127;
			motor[rightMotor]=-127;
		}
		else {
			motor[leftMotor]=0;
			motor[rightMotor]=0;
		}
	}
	motor[leftMotor]=0;
	motor[rightMotor]=0;
}


void goForward(int blocks){
	SensorValue[leftEncoder1]=0;
	SensorValue[rightEncoder1]=0;
	while(SensorValue(leftEncoder1)<(oneBlockTick*blocks)&&SensorValue(rightEncoder1)<(oneBlockTick*blocks)){
		motor[leftMotor]=127;
		motor[rightMotor]=127;
	}
	motor[leftMotor]=0;
	motor[rightMotor]=0;
}

void nada(){}

task autonomous() //Actual autonomous code
{
	if(blueFront==1){
		goForward(2);
	}
	else if(redFront==1){

	}
	else {
		nada();
	}


}

task usercontrol() //Interaction with controller starts once this task is initiated.
{
	while (true) //run forever, unless interupted by competition stand.
	{
	  motor[leftMotor]  = (vexRT[Ch3]); //left motors to channel 3(left stick up)
    motor[rightMotor] = (vexRT[Ch2])/2; //right motors to channel 2(right stick up)
		if(debugMode==true)
		{
			clearDebugStream();
			writeDebugStream("jump1: %i",jump1);
			writeDebugStream("jump2: %i",jump2);
		}
		if(vexRT[Btn8R] ==1)
		{
			while(!(SensorValue[potLeft]>=highest))
				{
					motor[liftMotor1]=78;
					motor[liftMotor2]=78;
				}
		}
		else if(vexRT[Btn8L] ==1)
		{
			if(SensorValue[potLeft]>baseHeight)
			{
				while(!(SensorValue[potLeft]<=baseHeight))
				{
					motor[liftMotor1]=-78;
					motor[liftMotor2]=-78;
				}
			}
			else if(SensorValue[potLeft]<baseHeight)
			{
				while(!(SensorValue[potLeft]>=baseHeight))
				{
					motor[liftMotor1]=78;
					motor[liftMotor2]=78;
				}
			}
		}
		else if(vexRT[Btn8U] ==1)
		{

				while(!(SensorValue[potLeft]>=highest))
				{
					motor[liftMotor1]=78;
					motor[liftMotor2]=78;
				}
				while(vexRT[Btn8U]==0){}
				time =nSysTime;
				while (!(nSysTime>=time+500)){
					motor[pickupMotor]=-100;
				}

		}
		else if(vexRT[Btn8D] ==1)
		{
				motor[pickupMotor]=120;
				if(SensorValue[potLeft]>pickupHeight)
				{
					while(!(SensorValue[potLeft]<=pickupHeight)){
					motor[liftMotor1]=-80;
					motor[liftMotor2]=-80;
					motor[pickupMotor]=120;
					}
				}
				if(SensorValue[potLeft]<pickupHeight)
				{
					while(!(SensorValue[potLeft]>=pickupHeight)){
					motor[liftMotor1]=80;
					motor[liftMotor2]=80;
					motor[pickupMotor]=120;
					}
				}
				motor[pickupMotor]=120;

				if(SensorValue[potLeft]>baseHeight)
				{
					while(!(SensorValue[potLeft]<=baseHeight)){
					motor[liftMotor1]=-80;
					motor[liftMotor2]=-80;
					motor[pickupMotor]=120;
					}
				}

				if(SensorValue[potLeft]<baseHeight)
				{
					while(!(SensorValue[potLeft]>=baseHeight)){
					motor[liftMotor1]=80;
					motor[liftMotor2]=80;
					motor[pickupMotor]=120;
					}
				}
		}


    if(vexRT[Btn6U] == 1)         // If button 6U (upper right shoulder button) is pressed:
    {
      motor[pickupMotor] = 127;
    }
    else if(vexRT[Btn6D] ==1){
    	motor[pickupMotor] = -127;
    }
    else{motor[pickupMotor]=0;
    	}



    if(vexRT[Btn5U] == 1)         // If button 6U (upper right shoulder button) is pressed:
    {
      motor[liftMotor1] = 127;
    }
    else if(vexRT[Btn5D] ==1){
    	motor[liftMotor1] = -127;
    }
    else{motor[liftMotor1]=0;}



    if(vexRT[Btn5U] == 1)         // If button 6U (upper right shoulder button) is pressed:
    {
      motor[liftMotor2] = 127;
    }
    else if(vexRT[Btn5D] ==1){
    	motor[liftMotor2] = -127;
    }
    else{motor[liftMotor2]=0;}


	}
}
