#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           liftMotor1,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           liftMotor2,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           pickupMotor,   tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)



//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)



#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!



void pre_auton()
{
  bStopTasksBetweenModes = true;

}

task autonomous()
{
while ( true){
drive_forward();
}
}

void drive_forward(){
	motor[leftMotor] = 127;
	motor[rightMotor] = 127;
}

task usercontrol()
{

	while (true)
	{
	  motor[leftMotor]  = (vexRT[Ch3]);  // (y + x)/2
    motor[rightMotor] = (vexRT[Ch2])/2;  // (y - x)/2

    if(vexRT[Btn6U] == 1)         // If button 6U (upper right shoulder button) is pressed:
    {
      motor[pickupMotor] = 127;
    }
    else if(vexRT[Btn6D] ==1){
    	motor[pickupMotor] = -127;
    }
    else{motor[pickupMotor]=0;}

    if(vexRT[Btn5U] == 1)         // If button 6U (upper right shoulder button) is pressed:
    {
      motor[liftMotor1] = 127;
    }
    else if(vexRT[Btn5D] ==1){
    	motor[liftMotor1] = -127;
    }
    else{motor[liftMotor1]=0;}

    if(vexRT[Btn5U] == 1)         // If button 6U (upper right shoulder button) is pressed:
    {
      motor[liftMotor2] = 127;
    }
    else if(vexRT[Btn5D] ==1){
    	motor[liftMotor2] = -127;
    }
    else{motor[liftMotor2]=0;}

	}
}
